services:
  postgres:
    image: 'postgres:16'
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-go_market}
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - '${PG_PORT_HOST:-5433}:5432'
